name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - name: Build C# code
      run: dotnet build
    - name: Run C# tests
      run: dotnet test
    - name: NPM Install
      working-directory: ./DotnetTemplate.Web
      run: npm install
    - name: Build TS code
      working-directory: ./DotnetTemplate.Web
      run: npm run build
    - name: Lint TS code
      working-directory: ./DotnetTemplate.Web
      run: npm run lint
    - name: Run TS tests
      working-directory: ./DotnetTemplate.Web
      run: npm t
    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  publish:
    if: github.ref_name == 'main'
    needs: build
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: taiwoolateju/dotnettemplate:${{ github.ref_name }}
  deploy:
    needs: publish
    name: Deploy Azure Webapp
    runs-on: ubuntu-latest
    steps:
    - name: Call Azure WebApp Webhook
      run: curl -dH -X POST ${{ secrets.AZURE_WEBHOOK }}
